name: hmdb

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  hmdb:
    runs-on: ubuntu-latest
    name: Test HMDB

    steps:
      # Step 1: Checkout the repository (for bash script (tba))
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Step 2: Install xml-twig-tools and process HMDB data
      - name: Process HMDB Data
        run: |
          # Install xml-twig-tools
          sudo apt-get install xml-twig-tools
                    
          # Create a directory to store processed data
          mkdir datasources/hmdb/results
          ls
          
          # Navigate to the HMDB directory
          cd datasources/hmdb/results
          
          # Download and extract HMDB metabolites data
          URL=$"http://www.hmdb.ca/system/downloads/current/hmdb_metabolites.zip"
          wget_output=$(wget -q "$URL")
          if [ $? -ne 0 ]; then
            echo "HMDB data not downloadable"
            exit 1
          else
            wget "$URL"
                  
          unzip hmdb_metabolites.zip
          
          # Split the XML file into smaller parts
          xml_split -v -l 1 hmdb_metabolites.xml
          
          # Remove the original XML file
          rm hmdb_metabolites.xml
          
          # Navigate back to the main directory
          cd ../
          
          # Create a zip archive of the processed data
          zip -r hmdb_metabolites_split.zip hmdb_data

      # Step 3: create and compare logfile (tba)
      - name: Compare data size 
        run: |
          echo "HMDB data has been succesfully downloaded"
          
      # Step 4: Commit and push logfile
     # - name: Commit and Push Logfile
      #  run: |
       #   git pull
          # Add the generated zip file
        #  git add datasources/hmdb/hmdb_metabolites_split.zip
          
          # Configure the user for the commit
         # git config --local user.email "action@github.com"
          #git config --local user.name "GitHub Action"
          
          # Commit changes
          #git commit -m "Automated test"
          
          # Push changes
          #git push
